---
- hosts: all
  tasks:
  - name: ensure apache is at the latest version
    apt: pkg=apache2 state=latest
  - name: ensure apache is running
    service: name=apache2 state=started
  - name: copy test file
    copy: src=umi dest=/var/www/html
