VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.hostname              = 'umi'
  config.vm.provider :digital_ocean do |provider, override|
    override.ssh.private_key_path = '~/.ssh/id_rsa'
    override.vm.box               = 'digital_ocean'
    override.vm.box_url="https://github.com/smdahlen/vagrant-digitalocean/
    raw/master/box/digital_ocean.box"
    provider.client_id            = 'Client IDを入力'
    provider.api_key              = 'API KEYを入力'
    provider.token                = 'tokenを入力'
    provider.image                = 'Ubuntu 14.04 x64'
    provider.region               = 'sgp1'
    provider.size                 = '512mb'
    provider.ssh_key_name         = 'publickey' # 公開鍵の名前
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.sudo = true
  end
end
